#!/bin/sh

xrdb -merge "$HOME/.Xresources"
setxkbmap -layout "latam" -model "pc105"
setxkbmap -option "altwin:alt_super_win"
xmodmap "$HOME/.Xmodmap"
emacs --daemon &
urxvtd -q -o -f &
compton &
redshift &
xsetroot -cursor_name left_ptr
xset s off -dpms r rate 500 30

exec fluxbox -log "$HOME/.fluxbox/log"
